# Default values for imachine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.cern.ch/docker.io/node
  pullPolicy: IfNotPresent
  tag: "20"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""



command: ["/usr/local/bin/npm", "install","&&","npm","run","start"]

service:
  type: ClusterIP
  port: 8080

mosquitto:
  replicaCount: 1
  image:
    repository: eclipse-mosquitto
    pullPolicy: IfNotPresent
    tag: "2"
  service:
    type: ClusterIP
    port: 1883
  ws_port: 9001
  path: /ws

podAnnotations: 
  eos.okd.cern.ch/mount-eos-with-credentials-from-secret: "eos-credentials"

workingDir: /eos/project-c/club-micro/projects/intelligence-machine/www

# eos:
#   username:
#   password: 