include:
  - component: '$CI_SERVER_FQDN/acc-co/devops/ksc-hq/ksc-ci-components/container@develop'
    inputs:
      docker-file: docker/Dockerfile
      gitlab-image: $CI_PROJECT_PATH/aframe-scene
      kaniko-build-args: "--build-arg NPM_AUTH_TOKEN=$NPM_AUTH_TOKEN"
      kaniko-working-dir: $CI_PROJECT_DIR/modules/aframe-scene
