include:
  - component: '$CI_SERVER_FQDN/acc-co/devops/ksc-hq/ksc-ci-components/container@v0.4.7'
    inputs:
      docker-file: modules/aframe-scene/docker/Dockerfile
      docker-path: modules/aframe-scene/docker
      gitlab-image: $CI_PROJECT_PATH/aframe-scene
