image:
  repository: gitlab-registry.cern.ch/cmcrobotics/workshops/intelligence-machine/aframe-scene
  pullPolicy: Always
  tag: "develop"

imagePullSecrets:
  - name: gitlab-registry

domain: inmachine.app.cern.ch

route:
  enabled: true
  
config:
  mqttBrokerUrl: "wss://inmachine-mqtt.app.cern.ch" 

mosquitto:
  enabled: true
  wsDomain: "inmachine-mqtt.app.cern.ch" # If empty, will default to mqtt-{{ .Values.domain }}
  image:
    repository: eclipse-mosquitto
    tag: 2.0.18
  service:
    type: ClusterIP
    wsPort: 9001
    mqttPort: 1883

ingress:
  enabled: false
