{{- if .Values.mosquitto.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mosquitto
          securityContext: {}
          image: "{{ .Values.mosquitto.image.repository }}:{{ .Values.mosquitto.image.tag }}"
          ports:
            - containerPort: 1883
            - containerPort: 9001
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: data
              mountPath: /mosquitto/data
            - name: log
              mountPath: /mosquitto/log
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
        - name: data
          emptyDir: {}
        - name: log
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true

    listener 9001
    protocol websockets
    allow_anonymous true

    persistence true
    persistence_location /mosquitto/data/
    log_dest file /mosquitto/log/mosquitto.log
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  type: {{ .Values.mosquitto.service.type }}
  ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
    - port: 9001
      targetPort: 9001
      name: ws
  selector:
    app: mosquitto
{{- end -}}
