{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: aframe-scene
  labels:
    app: aframe-scene
spec:
  host: {{ .Values.domain }}
  to:
    kind: Service
    name: aframe-scene
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mosquitto-ws
  labels:
    app: mosquitto
spec:
  host: {{ .Values.mosquitto.wsDomain | default (printf "mqtt-%s" .Values.domain) }}
  to:
    kind: Service
    name: mosquitto
    weight: 100
  port:
    targetPort: ws
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end -}}
